sudo: required

services:
  - docker

# Installing a newer Docker version
addons:
  apt:
    packages:
      - docker-ce

language: java

before_install:
  - docker --version
  - docker pull ghusta/postgres-world-db:2.2
  - docker run -d --name pg-flyway-world-db -p 5520:5432 ghusta/postgres-world-db:2.2
  - docker ps

install:
  - mvn dependency:go-offline -B -V

script:
  - mvn compile
  - mvn flyway:info -P travis-ci
  - mvn flyway:baseline -Dflyway.baselineVersion=1.0 -P travis-ci
  - mvn flyway:migrate -P travis-ci
  - mvn flyway:info -P travis-ci
