= db_flyway_sample

image:https://travis-ci.org/ghusta/db_flyway_sample.svg?branch=existing-db-world[Build Status,link=https://travis-ci.org/ghusta/db_flyway_sample]

This is an easy example how to create database migrations with http://flywaydb.org/[Flyway]

Please note that more information is given in the related blog articles on the topic:
https://blog.codecentric.de/en/2017/01/flyway-tutorial-managing-database-migrations/[Managing Database Migrations] and https://blog.codecentric.de/en/2017/01/flyway-tutorial-execute-migrations-using-maven/[Execute Migrations using Maven]

It is based on PostgreSQL database and should run right away after checking it out, if your postgres-server is up and running.
You might need to add password to the create- and drop-scripts depending on your database configuration for the postgres-user.
Of course you can also easily switch the example to make use of another database by changing JDBC imports and URL.

== Database initialisation

As it is not possible to create a new database with Flyway this needs to be done outside of Flyway.
The same is true for creating the database user that is used.

=== Method 1 : with psql client on existing server

To do this there are two convenience scripts:

* createDatabaseAndUser.sh
* dropDatabaseAndUser.sh

=== Method 2 : using Docker

Simply create a container which will create the needed database and user at start.

[source,bash]
----
docker run -d –name pg-flyway -p 5510:5432 -e POSTGRES_DB="flywaydemo" -e POSTGRES_USER="flywaydemo" -e POSTGRES_PASSWORD="flywaydemo123" postgres:latest
----

== Execution using Maven

To execute the example just execute the create-script and then you can execute Flyway using Maven. Please take a look at the link:./pom.xml[POM-file] to check the Flyway configuration.

[source,bash]
----
mvn flyway:info

mvn clean compile flyway:migrate
----

The Flyway configuration is loaded from the https://flywaydb.org/documentation/maven/#overriding-order[following order] (system properties first, then env vars, etc.).

If we only want to apply a particular migration (let's say v1.1), we can specify it with :


[source,bash]
----
mvn flyway:migrate -Dflyway.target=1.1
----

== Execution using the Command Line Tool

Install the Flyway Command Line Tool according to http://flywaydb.org/documentation/commandline/[these instructions]

Then execute the following command from the command line.
The configuration file link:./flyway.conf[flyway.conf] contains all the needed configuration for execution from the command line.
The good thing is that Flyway already comes with JDBC drivers for http://flywaydb.org/documentation/commandline/[a good amount of database systems] including PostgreSQL.
Thus there is no need to install anything in addition here.

[source,bash]
----
flyway migrate
----

_Generated with https://asciidoctor.org/[Asciidoctor] {asciidoctor-version}_